### PR TITLE
Models

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by SCOTPAUL** [comment]
The models are mostly done but the admin site needs cleaning up, I don't think it's ready to merge.

**Comment by projectgoav** [comment]
I think we should pull it just now. Means the merge conflicts are easier now, rather than later when we have many more problems.

**Comment by projectgoav** [comment]
I'll fix the issues the now on models branch so they will commit in-time -> when you think it's ready.

**Comment by SCOTPAUL** [comment]
OK, that's fair enough. I just had pretty messy code in places for testing, but since we need the back end done before everything else, I suppose we could do it in master.

**Comment by projectgoav** [comment]
As of d9953b5, merge conflicts should be gone. This was cause as not all branches had been updated after our changes in the team meeting today!

**Pull request merged**
